### ISSUE TITLE
Moving the "Remember Me" checkbox

### ISSUE THREAD

**Issue by jds0102** [mswysocki/Madison-Student-Apartment-Finder#20]
The remember me checkbox on the banner and in /views/sessions/new are in somewhat awkward places.

**Comment by aeggum** [comment]
This should also be done for the reset password link.

**Comment by cromdenne** [comment]
I branched and cleaned up a lot of the CSS throughout the site.  The next thing will be to clean up the add/update listing pages (and add the comments/reviews styling), and to style the forgot password page.  I'm just mentioning it here because I also cleaned up the banner with the two links mentioned in this thread, so I'm going to close this issue.
