### ISSUE TITLE
Comment about admin login

### ISSUE THREAD

**Issue by kongyang80** [mswysocki/Madison-Student-Apartment-Finder#34]
Severity: Low

Since I figured what the admin email without looking at the code, I was trying to log in as admin. 

When you enter an invalid login, it brings you to the Sign in page. If I enter the admin email in the top bar with no password, it won't let me in. If I type in the admin email with no password in the Sign in page, I get in. Weird. Are the two "Sign In" button doing different authentication? Did you guys remove the admin password?

**Comment by aeggum** [comment]
Hmmm.  I thought they were the same. 

Thanks, weird.  I'll take a look at this when I can.  May just be a misplaced call to a controller. 

Appreciated.

**Comment by aeggum** [comment]
I reset the password of that admin and it looks like the you cannot log-in without a password anymore, so that's good.  But there is still something off.
Somehow the password had been reset to nothing (which shouldn't be allowed), but the main page login functionality isn't the same as the specific log-in page. 

I'll investigate it when I get the chance.

**Comment by aeggum** [comment]
It looks like this was just a case of the validations in our model no longer holding, due to a bug elsewhere.  It cannot be reproduced as of now, the validations are fixed.
