### ISSUE TITLE
Clean up UI issues by demo

### ISSUE THREAD

**Issue by aeggum** [mswysocki/Madison-Student-Apartment-Finder#49]
Cory and I realized that using bootstrap unfortunately doesn't seem like it will work in Rails 3.0.9..so we'll have to stick with what we have for the demo.  

For the demo we should try to clean up a lot of the issues with the current UI: things coming off the page, static sizes of divs, etc.  There are probably issues for a lot of them already.  That way things will be a lot more presentable.

**Comment by xibaca** [comment]
Yeah, is anybody already working on the "show listing" page? I can reorganize the layout, change the comments area and fix the padding and margin issues.

**Comment by aeggum** [comment]
Cory mentioned that he was going to be doing that and the add a listing page tonight, but I don't know if he's started on anything yet.

**Comment by xibaca** [comment]
I see, I'm still configuring stuff here. I hope I don't have any hard issue with ImageMagick, otherwise I'll work using a linux virtual machine. I found a binary installer for windows, but 'bundle install' seem to be unable to find it. I'll give a try with their dynamic version of the lib, if that doesn't work right away I'll try using the vm.
